name: Run test script and commit results

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python dependencies
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install additional dependencies (if any)
        run: |
          python -m pip install requests

      - name: Run the test script
        run: |
          python lists.py
     
      - name: Get directory
        run: ls

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: merged_blocklist
          path: merged_blocklist.txt

      - name: Commit test results (requires push access)
        uses: actions/checkout@v3
        if: success()
        with:
          fetch-depth: 0

      - name: Configure Git (requires push access)
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add merged_blocklist.txt
        if: success()

      - name: Commit changes (requires push access)
        run: |
          git commit -m "Upload test results from workflow"
        if: success()

      - name: Push changes (requires push access)
        run: |
          git push origin main
        if: success()
