---
name: create lists

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python dependencies
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install additional dependencies (if any)
        run: |
          python -m pip install requests

      - name: Run the test script
        run: |
          python lists.py

      - name: Upload test artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: test_results.log
