name: Run test script and commit results

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install additional dependencies (if any)
        run: |
          cd $GITHUB_WORKSPACE; 
          python -m pip install requests

      - name: Run the test script
        run: |
          cd $GITHUB_WORKSPACE
          python lists.py
     
      - name: Get directory
        run: ls; pwd; echo $GITHUB_WORKSPACE

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: merged_blocklist
          path: merged_blocklist.txt

      - name: Commit test results (requires push access)
        uses: actions/checkout@v3
        if: success()
        with:
          fetch-depth: 0

